// ============================================================
// MINOR ARCANA — cardData.ts extension
// Task #92 — Aura category mapping, all 56 Minor Arcana cards
// Locked: April 2026
//
// auraContext values: 'breakthrough' | 'shadow' | 'neutral'
// Definitions:
//   breakthrough — upward energy, movement, clarity, expansion
//   shadow       — tension, resistance, complexity, friction
//   neutral      — holding, transition, observation, pause
//
// Add to existing cardData array in src/features/daily-draw/cardData.ts
// ============================================================

// ─────────────────────────────────────────
// WANDS — Fire / Casper
// ─────────────────────────────────────────

  {
    id: 'wands-ace',
    name: 'Ace of Wands',
    suit: 'wands',
    number: 1,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'breakthrough',
  },
  {
    id: 'wands-02',
    name: 'Two of Wands',
    suit: 'wands',
    number: 2,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'neutral',
  },
  {
    id: 'wands-03',
    name: 'Three of Wands',
    suit: 'wands',
    number: 3,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'breakthrough',
  },
  {
    id: 'wands-04',
    name: 'Four of Wands',
    suit: 'wands',
    number: 4,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'breakthrough',
  },
  {
    id: 'wands-05',
    name: 'Five of Wands',
    suit: 'wands',
    number: 5,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'shadow',
  },
  {
    id: 'wands-06',
    name: 'Six of Wands',
    suit: 'wands',
    number: 6,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'breakthrough',
  },
  {
    id: 'wands-07',
    name: 'Seven of Wands',
    suit: 'wands',
    number: 7,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'shadow',
  },
  {
    id: 'wands-08',
    name: 'Eight of Wands',
    suit: 'wands',
    number: 8,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'breakthrough',
  },
  {
    id: 'wands-09',
    name: 'Nine of Wands',
    suit: 'wands',
    number: 9,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'shadow',
  },
  {
    id: 'wands-10',
    name: 'Ten of Wands',
    suit: 'wands',
    number: 10,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'shadow',
  },
  {
    id: 'wands-page',
    name: 'Page of Wands',
    suit: 'wands',
    number: 11,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'breakthrough',
  },
  {
    id: 'wands-knight',
    name: 'Knight of Wands',
    suit: 'wands',
    number: 12,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'breakthrough',
  },
  {
    id: 'wands-queen',
    name: 'Queen of Wands',
    suit: 'wands',
    number: 13,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'breakthrough',
  },
  {
    id: 'wands-king',
    name: 'King of Wands',
    suit: 'wands',
    number: 14,
    element: 'fire',
    avatar: 'casper',
    auraContext: 'breakthrough',
  },

// ─────────────────────────────────────────
// CUPS — Water / Destiny
// ─────────────────────────────────────────

  {
    id: 'cups-ace',
    name: 'Ace of Cups',
    suit: 'cups',
    number: 1,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'breakthrough',
  },
  {
    id: 'cups-02',
    name: 'Two of Cups',
    suit: 'cups',
    number: 2,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'breakthrough',
  },
  {
    id: 'cups-03',
    name: 'Three of Cups',
    suit: 'cups',
    number: 3,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'breakthrough',
  },
  {
    id: 'cups-04',
    name: 'Four of Cups',
    suit: 'cups',
    number: 4,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'shadow',
  },
  {
    id: 'cups-05',
    name: 'Five of Cups',
    suit: 'cups',
    number: 5,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'shadow',
  },
  {
    id: 'cups-06',
    name: 'Six of Cups',
    suit: 'cups',
    number: 6,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'neutral',
  },
  {
    id: 'cups-07',
    name: 'Seven of Cups',
    suit: 'cups',
    number: 7,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'shadow',
  },
  {
    id: 'cups-08',
    name: 'Eight of Cups',
    suit: 'cups',
    number: 8,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'neutral',
  },
  {
    id: 'cups-09',
    name: 'Nine of Cups',
    suit: 'cups',
    number: 9,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'breakthrough',
  },
  {
    id: 'cups-10',
    name: 'Ten of Cups',
    suit: 'cups',
    number: 10,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'breakthrough',
  },
  {
    id: 'cups-page',
    name: 'Page of Cups',
    suit: 'cups',
    number: 11,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'neutral',
  },
  {
    id: 'cups-knight',
    name: 'Knight of Cups',
    suit: 'cups',
    number: 12,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'neutral',
  },
  {
    id: 'cups-queen',
    name: 'Queen of Cups',
    suit: 'cups',
    number: 13,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'neutral',
  },
  {
    id: 'cups-king',
    name: 'King of Cups',
    suit: 'cups',
    number: 14,
    element: 'water',
    avatar: 'destiny',
    auraContext: 'neutral',
  },

// ─────────────────────────────────────────
// SWORDS — Air / Eli
// ─────────────────────────────────────────

  {
    id: 'swords-ace',
    name: 'Ace of Swords',
    suit: 'swords',
    number: 1,
    element: 'air',
    avatar: 'eli',
    auraContext: 'breakthrough',
  },
  {
    id: 'swords-02',
    name: 'Two of Swords',
    suit: 'swords',
    number: 2,
    element: 'air',
    avatar: 'eli',
    auraContext: 'shadow',
  },
  {
    id: 'swords-03',
    name: 'Three of Swords',
    suit: 'swords',
    number: 3,
    element: 'air',
    avatar: 'eli',
    auraContext: 'shadow',
  },
  {
    id: 'swords-04',
    name: 'Four of Swords',
    suit: 'swords',
    number: 4,
    element: 'air',
    avatar: 'eli',
    auraContext: 'neutral',
  },
  {
    id: 'swords-05',
    name: 'Five of Swords',
    suit: 'swords',
    number: 5,
    element: 'air',
    avatar: 'eli',
    auraContext: 'shadow',
  },
  {
    id: 'swords-06',
    name: 'Six of Swords',
    suit: 'swords',
    number: 6,
    element: 'air',
    avatar: 'eli',
    auraContext: 'neutral',
  },
  {
    id: 'swords-07',
    name: 'Seven of Swords',
    suit: 'swords',
    number: 7,
    element: 'air',
    avatar: 'eli',
    auraContext: 'shadow',
  },
  {
    id: 'swords-08',
    name: 'Eight of Swords',
    suit: 'swords',
    number: 8,
    element: 'air',
    avatar: 'eli',
    auraContext: 'shadow',
  },
  {
    id: 'swords-09',
    name: 'Nine of Swords',
    suit: 'swords',
    number: 9,
    element: 'air',
    avatar: 'eli',
    auraContext: 'shadow',
  },
  {
    id: 'swords-10',
    name: 'Ten of Swords',
    suit: 'swords',
    number: 10,
    element: 'air',
    avatar: 'eli',
    auraContext: 'shadow',
  },
  {
    id: 'swords-page',
    name: 'Page of Swords',
    suit: 'swords',
    number: 11,
    element: 'air',
    avatar: 'eli',
    auraContext: 'neutral',
  },
  {
    id: 'swords-knight',
    name: 'Knight of Swords',
    suit: 'swords',
    number: 12,
    element: 'air',
    avatar: 'eli',
    auraContext: 'shadow',
  },
  {
    id: 'swords-queen',
    name: 'Queen of Swords',
    suit: 'swords',
    number: 13,
    element: 'air',
    avatar: 'eli',
    auraContext: 'breakthrough',
  },
  {
    id: 'swords-king',
    name: 'King of Swords',
    suit: 'swords',
    number: 14,
    element: 'air',
    avatar: 'eli',
    auraContext: 'breakthrough',
  },

// ─────────────────────────────────────────
// PENTACLES — Earth / Olivia
// ─────────────────────────────────────────

  {
    id: 'pentacles-ace',
    name: 'Ace of Pentacles',
    suit: 'pentacles',
    number: 1,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'breakthrough',
  },
  {
    id: 'pentacles-02',
    name: 'Two of Pentacles',
    suit: 'pentacles',
    number: 2,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'neutral',
  },
  {
    id: 'pentacles-03',
    name: 'Three of Pentacles',
    suit: 'pentacles',
    number: 3,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'breakthrough',
  },
  {
    id: 'pentacles-04',
    name: 'Four of Pentacles',
    suit: 'pentacles',
    number: 4,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'shadow',
  },
  {
    id: 'pentacles-05',
    name: 'Five of Pentacles',
    suit: 'pentacles',
    number: 5,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'shadow',
  },
  {
    id: 'pentacles-06',
    name: 'Six of Pentacles',
    suit: 'pentacles',
    number: 6,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'neutral',
  },
  {
    id: 'pentacles-07',
    name: 'Seven of Pentacles',
    suit: 'pentacles',
    number: 7,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'neutral',
  },
  {
    id: 'pentacles-08',
    name: 'Eight of Pentacles',
    suit: 'pentacles',
    number: 8,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'breakthrough',
  },
  {
    id: 'pentacles-09',
    name: 'Nine of Pentacles',
    suit: 'pentacles',
    number: 9,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'breakthrough',
  },
  {
    id: 'pentacles-10',
    name: 'Ten of Pentacles',
    suit: 'pentacles',
    number: 10,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'breakthrough',
  },
  {
    id: 'pentacles-page',
    name: 'Page of Pentacles',
    suit: 'pentacles',
    number: 11,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'neutral',
  },
  {
    id: 'pentacles-knight',
    name: 'Knight of Pentacles',
    suit: 'pentacles',
    number: 12,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'neutral',
  },
  {
    id: 'pentacles-queen',
    name: 'Queen of Pentacles',
    suit: 'pentacles',
    number: 13,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'breakthrough',
  },
  {
    id: 'pentacles-king',
    name: 'King of Pentacles',
    suit: 'pentacles',
    number: 14,
    element: 'earth',
    avatar: 'olivia',
    auraContext: 'breakthrough',
  },

// ─────────────────────────────────────────
// AURA DISTRIBUTION SUMMARY (for QA)
// Wands:     breakthrough ×9, shadow ×4, neutral ×1
// Cups:      breakthrough ×5, shadow ×3, neutral ×6
// Swords:    breakthrough ×3, shadow ×8, neutral ×3
// Pentacles: breakthrough ×7, shadow ×2, neutral ×5
// Total 56:  breakthrough ×24, shadow ×17, neutral ×15
// ─────────────────────────────────────────
